permalink: ./:year/:month/:day/:title.html
pygments: true
baseurl: /
# Changes the directory where Jekyll will look to transform files
source:             ./
# # Changes the directory where Jekyll will write files to
destination:        ./_site
# # Changes the directory where Jekyll will look for plugins
#
# post to display per pages
paginate: 5

