permalink: /:year/:month/:day/:title.html
highlighter: pygments
# #baseurl: /
# Changes the directory where Jekyll will look to transform files
source:             ./
# # Changes the directory where Jekyll will write files to
destination:        ./_site
# # Changes the directory where Jekyll will look for plugins
#
# post to display per pages
paginate: 5

navigation:
- title: Home
  url: /
- title: Archives
  url: /pages/archives.html
- title: Tags
  url: /pages/tags.html
- title: Projects
  url: /pages/projects.html

